### ISSUE TITLE
Can't setAttribute from an image element dataset 

### ISSUE THREAD

**Issue by iloverails** [webrecorder/wombat#103]
Hey, I'm trying to figure out why some of lazy loading images are not loading, for example one of my archived site contains `yall.js` lib with this line: 
```
element.setAttribute("src", element.dataset.src)
```
It's trying to lazy load images, but seems like wombat has overridden setter for `src` attribute or something else. Because for example I tried to replace that part of code and  these variants work fine:
```
element.src = element.dataset.src
```
```
element.setAttribute("src", element.getAttribute("data-src"))
```

Could you help me find please where is the wombat's line which replaces src attribute setter? Or why it's not working.

Thank you!

**Comment by ikreymer** [comment]
It's hard to say exactly, but hopefully something that's an easy fix.
Do you have an example of the live site / or WARC/WACZ file that has the issue? Can take a look, you can also send via email if you'd like.

**Comment by iloverails** [comment]
Thank you so much for the answer, you can test it here https://replayweb.page/ with this archive https://drive.google.com/file/d/1kMsV2n4z7KkTRN5EKMGCSWezIa91vHhV/view?usp=share_link, there are some lazy resources are not loading https://gyazo.com/74e5f7cf13c0fd1dd3189d2e137cc387

**Comment by ikreymer** [comment]
@iloverails The fix has now been released in replayweb.page 1.7.9

**Comment by iloverails** [comment]
cool, thank you!
