### ISSUE TITLE
Browsers making document.domain immutable

### ISSUE THREAD

**Issue by anjackson** [webrecorder/wombat#120]
According to this, `document.domain` will be modified so it can't be changed. See https://developer.chrome.com/blog/document-domain-setter-deprecation/

Wombat does mention `document.domain` so I'm wondering if this is going to break web archives and if there's anything we can do about it?

https://github.com/webrecorder/wombat/blob/ab919335805454f70b89aa5f54f0f908144a1f4a/src/wombat.js#L4834

**Comment by ikreymer** [comment]
I think this is intended for setting document.domain to relax cross-origin policies, which isn't how wombat is using this. Instead, we override it so that the native implementation is never called in the first place, so it shouldn't really affect things, but would be good to check just in case.

**Comment by ikreymer** [comment]
Seems to be fine in latest version of Chrome (115) with document.domain overrides disabled. The way wombat uses `document.domain` is with a custom override, which still works:

```
Object.defineProperty(document, "domain", {value: "foo"});
#document
document.domain
'foo'
```

Closing for now.
