### ISSUE TITLE
document.close in HTML templates

### ISSUE THREAD

**Issue by robertvanloenhout** [webrecorder/wombat#131]
Wombat changes <script> content when it is being used as a HTML template to add a ';document.close()' statement.
I have seen this happen on a website that uses Ninja Forms
https://developer.ninjaforms.com/codex/custom-field-templates/
which uses <script type="text/template">

I have seen similar constructs being used in AngularJS.

The result of this is that the page being displayed will contain ';document.close();' text.

I think this is related to the wombat injectDocClose feature which is set to true in wabac.js

**Comment by ikreymer** [comment]
Do you have an example page or archive where this is happening? It should be skipping scripts that have a `text/template` type, with the check here: https://github.com/webrecorder/wombat/blob/main/src/wombat.js#L2139

**Comment by ikreymer** [comment]
Ah ok, I see the issue on the page you specified - hm, it may not be related to this specifically, but something to do with `<template>` where the template gets added at the bottom..

**Comment by robertvanloenhout** [comment]
Here is an example of a website where this problem occurs.
https://www.gigharborfire.org/contact-us/contact-form/
