### ISSUE TITLE
"Results" sections of developer.mozilla.org are not showing up

### ISSUE THREAD

**Issue by benoit74** [webrecorder/wombat#156]
Nota: I open the issue on wombat because both warc2zim and replayweb.page are impacted, but this would be something to fix in wabac and warc2zim indeed.

Sample original web page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

Sample WARC: https://tmp.kiwix.org/ci/test-warc/crawl-devmdn-bcd-20240531.warc.gz

Result on replayweb.page: all "RESULT" sections are blank

![image](https://github.com/webrecorder/wombat/assets/7102089/b17bb047-47f2-42f5-903e-da6ca729307e)

I tried to investigate a bit but struggled to find an explanation for now.

**Comment by ikreymer** [comment]
Thanks for the report! Appears to be an easy fix here, was not handling `postMessage(msg, options)`, which MDN seems to be using, only `postMessage(msg, targetOrigin, transfer)` and adding a check for that as well

**Comment by benoit74** [comment]
Despite using wombat 3.7.8, this is still not working inside a ZIM. Any clue of where I should have a look at? Everything else on the page is working properly now (including the top iFrame with is now working since I set `isSW: false`)

If needed there is a test ZIM at https://tmp.kiwix.org/ci/test-warc/devmdn-bcd_2024-06.zim
