### ISSUE TITLE
Youtube player is not working when wombat is configured to not run inside a Service Worker

### ISSUE THREAD

**Issue by benoit74** [webrecorder/wombat#158]
We have an issue in warc2zim where when I configure wombat.js to not run inside a Service Worker (`isSW: false` in call to `_WBWombatInit`), then the Youtube player is not working anymore.

Since we are not using anymore a service worker with warc2zim v2, this is however the recommended setting, as discussed in https://github.com/webrecorder/wombat/issues/155#issuecomment-2183191941 and following comments.

The difference I see is that with SW mode, the player data is loaded from a URL like `youtube.fuzzy.replayweb.page/youtubei/v1/player?videoId=hQXa6TkSeH0` while when SW is deactivated, the player data is loaded from a URL like `www.youtube.com/youtubei/v1/player?prettyPrint=false`. And for sure, we have data in the WARC / ZIM at first URL but not at second one (taking into account the fuzzy rewriting of course).

Does it ring any bells to you? Is it a problem in warc2zim? Thank you in advance!

**Comment by ikreymer** [comment]
> Does it ring any bells to you? Is it a problem in warc2zim? Thank you in advance!

Hm, do you have an example ZIM? I think there maybe other rewriting issues, not sure that its related to wombat but can double check.

**Comment by benoit74** [comment]
Sure, thank you for investigating this!

I've uploaded a test [WARC](https://tmp.kiwix.org/ci/test-youtube-nosw/crawl-orca-20240708.warc.gz) and corresponding ZIMs with the service worker setting set to [true](https://tmp.kiwix.org/ci/test-youtube-nosw/100r.co_en_tests-orca-withsw_2024-07.zim) (player is working) and set to [false](https://tmp.kiwix.org/ci/test-youtube-nosw/100r.co_en_tests-orca-nosw_2024-07.zim) (player is not working).

Sorry for not providing these files in the first place and making you context-switching ...

**Comment by benoit74** [comment]
How can I help you investigate this a bit further. I'm struggling to understand what is going on here, and would definitely like to set this `isSW: false` setting to have proper operation overall ...

At the same time I totally understand it is far from your main concerns ... so no worries, I'm just trying to figure out a way forward.

**Comment by ikreymer** [comment]
I'm pretty sure I found the issue: the convert-POST-to-get override in XHR requests was only being applied as part of the service worker-based override, so the fuzzy matching in wombatSetup that you have were not being matched, since it only works with GET requests.
This should be fixed with: https://github.com/webrecorder/wombat/tree/convert-to-get-fix-without-sw
Looks like warc2zim is already setting that to true, so should be good.
@benoit74 can you test it out with this branch to confirm?

**Comment by benoit74** [comment]
@ikreymer thank you, tested successfully on our test website WARC, this works like a charm! (with `isSW: false` and `convert_post_to_get:true`, as suggested / expected)
