### ISSUE TITLE
iFrame is not working in non-Service worker mode

### ISSUE THREAD

**Issue by benoit74** [webrecorder/wombat#164]
This issue is closely related to https://github.com/webrecorder/wombat/issues/158, but still a bit different so I'm opening a distinct one.

Problem occurs in warc2zim where we use wombat to replay inside the ZIM.

Page where the problem occur is https://womenshistory.si.edu/events/mysterious-mrs-nixon

Test WARC and ZIM with only this page can be found at https://tmp.kiwix.org/ci/test-warc/women-history/

Problem was first that the iframe was not rendered at all first (because we inadequately set the `isSw: true` in wombat setup. This is known that we need to set it to `isSw: false` for warc2zim 2.

Despite setting it to `isSw: false` (which is the case in test ZIM), we now have a weird iframe content. WARC is working on replayweb.page, so this is clearly not a crawling issue.

![image](https://github.com/user-attachments/assets/e7803fde-d16a-4880-8f19-5ff8789ea826)

I need help to investigate/fix this issue.

Warc2zim issue is https://github.com/openzim/warc2zim/issues/364

**Comment by benoit74** [comment]
I don't achieve to get a hold on the reason behind it, but this is now working OK. Even with "old" wombat versions and same WARC which cause the issue ... something else fixed the thing probably ...
Sorry for that, but at least no work needed!

**Comment by ikreymer** [comment]
Glad that it's working now!
