### ISSUE TITLE
Wombat rewriting prevents website from loading

### ISSUE THREAD

**Issue by benmayersohn** [webrecorder/wombat#20]
I also wrote this as [issue 521](https://github.com/webrecorder/pywb/issues/521) in Pywb, but I think the problem is primarily with wombat.js and not pywb itself. I'll keep both issues open until it's clear who the real culprit is.

---

## Describe the bug

I'm attempting to record the website [http://supermegaslot.com/demo/game.php?game=3013](http://supermegaslot.com/demo/game.php?game=3013), which is a free demo of a slot machine game, using pywb. However, nothing loads on the screen when using either WebRecorder or pywb locally. Looking at the console, I have a few errors that have something to do with the `loader.js` file that is loaded initially. A few of the errors (without specific line numbers or anything):

- `Uncaught SyntaxError: Identifier 'loader' has already been declared` 
- `Uncaught ReferenceError: loader is not defined`

**Note**: when using WebRecorder with a remote browser, it works fine. However, I want to use pywb to record many slot outcomes programmatically and it would be ideal if I could run this locally.

## Steps to reproduce the bug

Load this up in Chrome and look at the console errors:
[https://webrecorder.io/bmayers/demo-slots/20191112222854/http://supermegaslot.com/demo/game.php?game=3013](https://webrecorder.io/bmayers/demo-slots/20191112222854/http://supermegaslot.com/demo/game.php?game=3013)

## Expected behavior

A loading screen should appear, and then I should be able to play the slot game.

## Environment

- OS: MacOS Mojave
- Browser: Chrome
- Version: 78.0.3904.97

**Comment by benmayersohn** [comment]
I've concluded that the JS rewriter likely has trouble working with some scripts that are deliberately obfuscated. I was able to resolve the issue by dumping the website and making some changes to the scripts so the rewriter still works, then recording my sessions from localhost.

**Comment by ikreymer** [comment]
Hi, sorry didn't get to this earlier, would like to figure this out! Looks like its due to eval rewriting...

**Comment by benmayersohn** [comment]
Thanks for looking into it!

I think the problem is the order in which certain statements are (deliberately) written in the JS files. For example, if you look at `loader.js`, prototype statements are made before the `loader` function is even created at the very bottom.  Furthermore, the last statement creates an instance of class `loader` with the exact same name. I corrected this by writing the capitalized `Loader` when it refers to the class and leaving it lowercase for the instance, and moving the statement

```
function Loader() {}
```

to the top. The same had to be done for most of the JS files. Some of the files are also obfuscated. For example, look at `game.js`. Object names are stored in an array of hexidecimal strings, so one needs to look for the position of 'prototype' in this array to identify which instances of the "game" refer to the instance and which refer to the class.

The two aforementioned scripts are included here: [js_files.zip](https://github.com/webrecorder/wombat/files/3855225/js_files.zip)

**Comment by russinholi** [comment]
Hi, I got a similar problem while loading a warc of a website that uses a drupal script, where it declares a variable called 'window' like `var window=window`, and as the wombat.js prefixes the script with `let window = _____WB$wombat$assign$function_____("window");` 

I get this error:
```
  Uncaught SyntaxError: redeclaration of let window
  note: Previously declared at line 4, column 4
```

I'm not sure if this ticket is the best one to add this, but if not let me know if I should create a new one.

**Comment by ikreymer** [comment]
Site no longer live, no repro is possible, likely fixed with updates to wombat since then.
