### ISSUE TITLE
Image lazy loading

### ISSUE THREAD

**Issue by edsu** [webrecorder/wombat#23]
I don't have a sense of how common they are in the wild yet, but will [lazy loaded images](https://twitter.com/addyosmani/status/1227619409625174016) need to be auto-fetched?

**Comment by ikreymer** [comment]
Yeah, or a simpler option might be to just remove/rewrite the `loading=lazy` attribute if present.

**Comment by ikreymer** [comment]
Auto-capture of lazy loaded images is now handled via browsertrix behaviors (webrecorder/browsertrix-behaviors#23), moving auto-fetch implementations to there, as its something that only want to do when crawling.
Probably doesn't make sense to make part of core wombat, as don't want to do this always for replay.
