### ISSUE TITLE
Rewriting of URI's in the srcset attribute of image tags seems off

### ISSUE THREAD

**Issue by maeb** [webrecorder/wombat#80]
## Description
In the `srcset` attribute of `img` tags, the width descriptor (and probably pixel density descriptors) becomes part of the image URI joined by `%20` after rewriting.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset for reference.

## Example

`<img src="a.jpg" srcset="a300x400.jpg 700w, a800x800.jpg 800w">` gets rewritten to something like `<img ... srcset=".../a300x400.jpg%20700w, .../a800x800.jpg%20800w">`.

~~I am not 100% sure this is wombat's doing or if pywb has a hand in this.~~

Edit: The rewrite function is found here https://github.com/webrecorder/wombat/blob/72db79431401ad6d7449eb77c37a6a82b84113c8/src/wombat.js#L2022

It seems that the regex split ends up using `"...a.jpg 700w"` as `url` argument to the  `rewriteUrl(url, true, mod)` function. This then explains the percent encoded space `%20`.

**Comment by ikreymer** [comment]
Thanks for reporting, and sorry for delay in taking a look at this, yes, this should be fixed to do the same thing as what's happening in wabac.js, where the space is split off first before rewriting, eg:
https://github.com/webrecorder/wabac.js/blob/main/src/rewrite/html.js#L123
