### ISSUE TITLE
https://iteencamp.icac.hk/ capture logs wombat.js errors and fails to replay

### ISSUE THREAD

**Issue by galgeek** [webrecorder/wombat#95]
https://iteencamp.icac.hk/ captures from both webrecorder's ArchiveWeb.page and brozzler produce wombat.js console errors in replay, like

`Uncaught TypeError: Right-hand side of 'instanceof' is not callable`

The brozzler capture replays well, in contrast, in Archive-It's legacy Java Wayback:
https://jwb.archive-it.org/10883/20220709002816/https://iteencamp.icac.hk/

**Comment by ikreymer** [comment]
It looks like the page overrides the global Window object, so wombat should store a reference to the original.
